apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  # FileSystem or Block. we have folder so filesystem
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # belowes are available for many nodes
    # - ReadOnlyMain
    # - ReadWriteMany
  # type of volume
  # hostpath is only for development, and will work for only one node
  hostPath:
    path: /data
    type: DirectoryOrCreate
